### ISSUE TITLE
Implement GBSA

### ISSUE THREAD

**Issue by proteneer** [proteneer/timemachine#134]

**Comment by proteneer** [comment]
It looks like we will have to disable electrostatic exclusions for GBSA to work correctly. (We still keep vDw exclusions).

**Comment by proteneer** [comment]
@chuantian we will also need to test @j-wags new FF handler support which will necessitate us upgrading to the latest OFF (this will probably break a metric shit ton of things). Also @maxentile - do you have SMIRNOFF xml ready yet for your new GBSA parameters?

**Comment by chuantian** [comment]
Yeah, that makes sense! 
So, the electrostatics and GBSA won't have exclusion lists (all pairs will be computed), but the vdW will have 1-2, 1-3 excluded, 1-4 scaled, right?

**Comment by maxentile** [comment]
>Also @maxentile - do you have SMIRNOFF xml ready yet for your new GBSA parameters?

Should still be able to get a draft to you by late this afternoon

**Comment by proteneer** [comment]
@maxentile Awesome - thanks!

**Comment by jchodera** [comment]
I think @maxentile and I concluded (by looking at `sander`) that we need to use exclusions/exceptions for electrostatics and LJ, but _not_ for the GB interactions.

**Comment by maxentile** [comment]
>I think @maxentile and I concluded (by looking at sander) that we need to use exclusions/exceptions for electrostatics and LJ, but not for the GB interactions.

Agreed!

**Comment by chuantian** [comment]
Sorry, what I said before was confusing. 
I agree with @jchodera and @maxentile, the electrostatics and vdw needs 1-2, 1-3 exclusion, 1-4 scaling. But GB do all pairs with no exclusion and scaling. This is what amber does as well (Confirmed!), and seems reasonable.

**Comment by maxentile** [comment]
>Also @maxentile - do you have SMIRNOFF xml ready yet for your new GBSA parameters?
>Should still be able to get a draft to you by late this afternoon

I've now re-run some of my numerical experiments using Parsley instead of smirnoff99frosst. Here are SMIRNOFF xml of draft parameters obtained by extracting the last iterate of a 10,000 step MCMC simulation targeting agreement to FreeSolv: https://github.com/openforcefield/bayes-implicit-solvent/blob/ebb01e436608204bda166391141fc0319635f149/bayes_implicit_solvent/gb_models/prototype_freesolv_informed_obc2_params.offxml

These elemental-type parameters are refit from mbondi parameters to improve fit between FreeSolv experimental hydration free energies and hydration free energy estimates obtained by reweighting vacuum samples collected using the OpenFF 1.0.0 Parsley forcefield. The apparent RMSE on FreeSolv subset (n=631) is improved from ~2.65 kcal/mol before GB fitting to ~1.77 kcal/mol after. This isn't the very best fit obtained, compared with other sampling variants and model variants considered in this project. With more thorough sampling and many different random initializations, the best elemental-type RMSE we've seen in this project is ~1.6kcal/mol. With a lot of atom-type elaboration, the RMSE has further improved to as low as ~1.4 kcal/mol. And switching to fingerprint-based parameter assignment + charge-hydration-asymmetry-corrected model form may further improve RMSE to as low as ~1 kcal/mol.

![pred_scatterplots](https://user-images.githubusercontent.com/5759036/74291885-5933db00-4d04-11ea-8a26-85987d0b27cc.png)
_reweighting-based estimates on Freesolv before and after fitting, colored by "improvement" (`|expt_i - initial_pred_i| - |expt_i - final_pred_i|`_

But it's hopefully somewhat conservative, hopefully not messing too much else up! There are a couple oddities though (e.g. the wildcard "scale" seems suspiciously small, and I'm not sure if I should be surprised that the radius parameter for phosphorus is smaller than everything else...).

![parsley_plus_obc2_sampled_radii_and_scales](https://user-images.githubusercontent.com/5759036/74291755-df9bed00-4d03-11ea-9807-7a3d2d337ca9.png)
_parameter trajectories of MCMC targeting fit to FreeSolv_

**I also will caution that I have yet to perform several important validations**, esp. checking that the hydration free energy predictions I get by running implicit-solvent MD using the new parameters are okay, and a few other checks that these parameters didn't overfit to some detail of how I formed estimates by reweighting vacuum samples! Assuming these validations check out, an important general limitation is that these are only informed by hydration free energies in FreeSolv, and have not been validated against any other property.

**Comment by chuantian** [comment]
Hi @maxentile I have one question, why the hydrogen has so large radii? Are those initial radii values from original GB model?

**Comment by maxentile** [comment]
>Hi @maxentile I have one question, why the hydrogen has so large radii? 

I'm not sure why! I don't interpret the radii that the GB model accepts as input as similar to vdW radii. They could be bigger or smaller than effective vdW radii if that improves predictions of hydration free energies, and depending on the associated "scale" parameters...

>Are those initial radii values from original GB model?

The initial radius value for hydrogen is a random perturbation of the mbondi parameter for hydrogen, which was 1.2Å.

**Comment by chuantian** [comment]
@maxentile 
I agree that the radii is not equivalent to vdW radii, but it should be very close. And apparently the radii is not GB effective radii either, which requires actual calculation on how solvent exposed or buried an atom is in MD simulation.  Therefore, if the radii deviates too much from the original value (1.2), making hydrogen similar to a carbonyl oxygen or an amide nitrogen, that's probably a sign of overfitting or error cancellation.

**Comment by maxentile** [comment]
>I agree that the radii is not equivalent to vdW radii, but it should be very close.

Okay!

>And apparently the radii is not GB effective radii either, which requires actual calculation on how solvent exposed or buried an atom is in MD simulation.

Yep! The radii the GB model accepts as input are "intrinsic radii," and effective Born radii are computed from these in a geometry-dependent way.

>Therefore, if the radii deviates too much from the original value (1.2), making hydrogen similar to a carbonyl oxygen or an amide nitrogen, that's probably a sign of overfitting or error cancellation.

This may well be overfitting to the properties that appear in the likelihood here, and I have not checked! We also often expect there to be directions in a model's parameter space by which the parameters can be adjusted without affecting the predictions too much, as long as other parameters "compensate" appropriately.

I think it is reasonable to try to limit how far the parameters wander away from an initially tolerable point in parameter space, if fitting to a limited set of properties and concerned about how changes might affect performance on properties not considered in current round of fitting. However, MCMC is _intended_ to do as much wayward wandering as possible!

**Comment by proteneer** [comment]
GBSA is now implemented. Closing this issue.

**Comment by proteneer** [comment]
@maxentile 

It looks like those parameters are *extremely* unstable for a standard protein-ligand system. Many of my simulations have been crashing with them. I've had to revert back to the original OBC2 parameters for now.

**Comment by maxentile** [comment]
Sorry to hear that. Reverting to OBC2 parameters is probably safest for applications.

These were exclusively fit to a collection of small molecule hydration free energies, and the primary study objective was to check "can we do MCMC with this target." As mentioned above and in warnings in the parameter file, stability of MD with the resulting parameters was not checked, and no other properties were validated against. I had also not considered using these parameters for protein systems. Without additional penalties (which we did not want to include in this study), it is likely that this procedure "overfits" to the properties appearing in the likelihood, and if the MCMC was efficient then it's also likely that the parameters diffused far away from "safe" initial point in parameter space along directions that are unconstrained by the properties appearing in the likelihood.
