### ISSUE TITLE
Fix Improper Torsions

### ISSUE THREAD

**Issue by proteneer** [proteneer/timemachine#136]
Currently we encode the valence terms using a ValenceDict which is keyed on the first and last atom index. This is incorrect and unsuitable for impropers, which require tre-foil support so the key uniqueness is no longer correct. We will need keep instead on the central atom and expand separately.

**Comment by chuantian** [comment]
The trefoil code we have is fine, the problem is, one single improper dihedral can match with smirks multiple times which result with multiple improper dihedrals. Then, we do trefoil on each of them which will overestimate improper torsion potentials. I'm fixing it now.
An example showing the problem is:
<ImproperTorsionType with smirks: [*:1]~[#7X3$(*~[#6X3]):2](~[*:3])~[*:4]  periodicity1: 2  phase1: 180.0 deg  k1: 1.0 kcal/mol  id: i3  >
[(14, 22, 43, 44), (14, 22, 44, 43), (43, 22, 14, 44), (43, 22, 44, 14), (44, 22, 14, 43), (44, 22, 43, 14)]
All the six elements are matched improper dihedrals, but we only need one of them and do trefoil on it, so we will have a list of 3 elements.

Another example is:
<ImproperTorsionType with smirks: [*:1]~[#6X3:2](~[*:3])~[*:4]  periodicity1: 2  phase1: 180.0 deg  k1: 1.1 kcal/mol  id: i1  >
[(0, 2, 8, 29), (0, 2, 29, 8)]
This time only two are matching, but we still need one of them and do trefoil on it.

**Comment by chuantian** [comment]
Taking H-C=O(-O) for an example. Currently, the improper torsion is doing well when a perturbation is acted on the central atom C . However, if a perturbation is acted on coordinate of any of the three atoms (H, O or O), the planarity won't be restored.
For instance acted on H, H will move to restore planarity, the C will also try to restore planar property by moving in the opposite direction (opposite against H), but the other two O atoms both move in same direction (same with H atom).

**Comment by chuantian** [comment]
Fixed for now! Through checking on a isolated system, the improper is working fine. From the previous argument on H-C=O(-O), it is actually showing improper is doing the right thing. 
The actual cause to the ring distortion could be something else in Time Machine.

**Comment by proteneer** [comment]
I'm closing this as fixed. Will open a separate issue for permutations later.
