### ISSUE TITLE
clean up Observables class

### ISSUE THREAD

**Issue by proteneer** [proteneer/timemachine#321]
Per offline discussion with @maxentile we should make a list of all the observables we may want in the near future. Some of the things that are missing are:

1) Coordinates observable
2) Energy observable

Feel free to add anything else that's missing

**Comment by maxentile** [comment]
A couple other possible considerations:
* A "time-series" version of an observable vs. an "accumulator" version of an observable (for example, if we want to capture all of the du/dl values from a trajectory for later processing, rather than just the mean and stddev of du/dl for a pre-specified window of a trajectory).
* A nonequilibrium work observable (time-series version: `w_t = u_{t+1}(x_t) - u_t(x_t)`, accumulator version: `w = \sum_t w_t`)
* Ideally want instances of the observable class to be serializable, just as the potentials are serializable

**Comment by proteneer** [comment]
Closing this due to staleness
