### ISSUE TITLE
Provide method to filter frames

### ISSUE THREAD

**Issue by badisa** [proteneer/timemachine#527]
Currently we write out a frame every 1000 steps with all of the coordinates. This consumes a lot of disk space when we often don't need a lot of the frames. Currently we only need the endpoint frames for training, and we could do future work to reduce that further.

Potential filters:

- Write out only the endpoints (lambda = 0, lambda = 1)
- Write out only coordinates that are within some distance of the ligand
- Write out complex frames without water

**Comment by maxentile** [comment]
+1 to this.

This filter could be made more stringent if optimized for RABFE specifically, where we may not even need all pairs of end points for reweighting -- just lambda=0 for the "conversion" stages.

(Since the lambda=1 endpoints for conversion stages don't depend on optimizable forcefield parameters, and the decoupling stages do not depend on optimizable forcefield parameters.)

**Comment by maxentile** [comment]
Closed by https://github.com/proteneer/timemachine/pull/528
